services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://gitlab.test.me'
#       Uncomment: set password for user root
#       see: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6320
#       gitlab_rails['initial_root_password'] = 'password'
    ports:
      - '8086:80'
      - '8443:443'
      - '822:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
